language: c

os:
  - osx
  # - linux

addons:
  apt:
    packages:
      - gfortran
      - autoconf
      - automake
      - libtool
      - libtool-bin
      - mpich
      - libmpich-dev 
    update: true
  # homebrew:
  #   packages:
  #     - gfortran
  #     - autoconf
  #     - automake
  #     - libtool
  #     - libtool-bin
  #     - openmpi
  #   update: true
    # brew update can take a long time and slow down your builds.

before_install:
  - test -n $CC && unset CC
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install mpich; fi

script:
  - autoconf --version
  - automake --version
  - if [ $TRAVIS_OS_NAME = linux ]; then libtool --version ; else libtool -V ; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then mpichversion ; fi
  - autoreconf -i
  - ./configure --enable-profiling --enable-subfiling --enable-thread-safe --enable-burst_buffering --enable-shared --enable-debug pnc_ac_debug=yes 
  - make distcheck -s V=1 LIBTOOLFLAGS=--silent DISTCHECK_CONFIGURE_FLAGS="--silent --enable-profiling --enable-subfiling --enable-thread-safe --enable-burst_buffering --enable-shared --enable-debug pnc_ac_debug=yes"

after_success:
  - make -s distclean

after_failure:
  - cat ./config.log
  - make -s distclean

notifications:
  email: false

